### PR TITLE
Windows build

### PR DESCRIPTION
**Pull request by cmohl2013**
The PR is still work in progress. Tests fail currently, because new Pyilastik version 0.0.9 has to be released beforehands

https://github.com/yapic/pyilastik/pull/6

### CODE REVIEW

**Review by pranjaldhole — COMMENTED** [review]
It seems that build still fails for Windows even after updating the pyilastik to v0.0.9.
From the error log, it seems to be some kind of file reading error.
Could it be because of the syntax to define paths in Windows differs?
@cmohl2013 @dlesmesl ?

P.S. I discovered that if you want to rebuild the travis-ci without pushing a commit, you need to close and re-open the pull request.

**Comment by cmohl2013** [comment]
@pranjaldhole yes, seems to be a path naming problem. Unexpected to me, because we used either pathlib or os.path to handle path strings.

**Comment by cmohl2013** [comment]
One guess: All paths should be defined as absolute paths to work on Windows.

**Comment by cmohl2013** [comment]
I fixed the windows related path problems.

One problem concerning writing tif files is still not solved: 
`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\travis\\AppData\\Local\\Temp\\tmp3xq0tr14\\40width26height3slices_rgb_class_1.tif'`

**Comment by pranjaldhole** [comment]
@cmohl2013 I wonder if the error is because in the `test_put_tile_1` and `test_put_tile_2` the `os.remove(path)` is called twice.
I am still surprised though that Linux build can handle that well and not the Windows build.

**Comment by dlesmesl** [comment]
@cmohl2013 @pranjaldhole I search a bit about this error and found this [tempfile Winerror 32](https://www.logilab.org/blogentry/17873). I might say the tests are getting this error due to the way the `tempfile` is being used in the codes. I see from `test_put_tile_1` and `test_put_tile_2` that using `os.close()` should solve the issue. I don't really understand the error print with `test_prediction_loop` and `test_put_probmap_data_dimorder_zxyc` but I'd say is related with this problem too.

**Comment by cmohl2013** [comment]
@pranjaldhole @dlesmesl Thank you for your suggestions. I can easily replace the tempfile library with tempdir option that is available in pytest.

**Review by dlesmesl — APPROVED** [review]
Great! now it's passing all the tests, thank you for your effort!

**Review by pranjaldhole — APPROVED** [review]
I learnt how to write system specific flags while writing tests. Thanks, @cmohl2013!

**Comment by cmohl2013** [comment]
@pranjaldhole thank you for merging and release update!

**Pull request merged**
